### ISSUE TITLE
Uncaught TypeError: Cannot read property 'isVisible' of undefined

### ISSUE THREAD

**Issue by ramk18** [aidistan/atom-symbols-view-plus#11]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.17.2 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.5
**Thrown From**: [symbols-view-plus](https://github.com/aidistan/atom-symbols-view-plus) package 0.116.1-plus.2

### Stack Trace

Uncaught TypeError: Cannot read property 'isVisible' of undefined

```
At /Users/ramk/.atom/packages/symbols-view-plus/lib/go-to-view.js:9

TypeError: Cannot read property 'isVisible' of undefined
    at GoToView.toggle (/packages/symbols-view-plus/lib/go-to-view.js:9:19)
    at /packages/symbols-view-plus/lib/main.js:35:31)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:265:1)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:1)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:166:1)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (/Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:1306:1)
    at EventEmitter.outerCallback (/Applications/Atom.app/Contents/Resources/app/src/application-delegate.js:347:1)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -0:20.1.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-when-scrolling)
  2x -0:15.7.0 editor:consolidate-selections (input.hidden-input)
     -0:05.4.0 symbols-view-plus:go-to-declaration (span.syntax--entity.syntax--name.syntax--function.syntax--js)
```

### Non-Core Packages

```
activate-power-mode 2.0.0 
angular2-snippets 0.4.0 
angularjs 0.4.0 
atom-beautify 0.29.26 
atom-htmltidy 5.1.0 
atom-runner 2.7.1 
atom-typescript 11.0.3 
auto-detect-indentation 1.3.0 
autoclose-html 0.23.0 
busy-signal 1.4.3 
default-language 0.3.0 
editorconfig 2.2.2 
emmet 2.4.3 
file-icons 2.1.7 
git-blame 1.1.1 
git-plus 7.9.3 
git-time-machine 1.5.9 
highlight-selected 0.13.1 
intentions 1.1.2 
javascript-snippets 1.2.1 
linter 2.1.4 
linter-csslint 1.3.4 
linter-eslint 8.2.1 
linter-htmlhint 1.3.3 
linter-jshint 3.1.2 
linter-jsonlint 1.3.0 
linter-pylint 2.1.0 
linter-sass-lint 1.7.4 
linter-ui-default 1.6.0 
meteor-api 2.20.0 
meteor-helper 0.29.0 
minimap 4.28.2 
minimap-highlight-selected 4.6.1 
pigments 0.39.1 
platformio-ide-terminal 2.5.1 
script 3.15.0 
symbols-view-plus 0.116.1-plus.2 
todo-show 1.11.0 
```

**Comment by aidistan** [comment]
Thanks for reporting this issue. Has been fixed in v0.116.1-plus.3
