### ISSUE TITLE
Uncaught TypeError: Cannot read property 'substring' of undefined

### ISSUE THREAD

**Issue by mrunwal** [aidistan/atom-symbols-view-plus#19]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.22.1 x64
**Electron**: 1.6.15
**OS**: Ubuntu 16.04.3
**Thrown From**: [symbols-view-plus](https://github.com/aidistan/atom-symbols-view-plus) package 0.117.0-plus.1

### Stack Trace

Uncaught TypeError: Cannot read property 'substring' of undefined

```
At /home/manish/.atom/packages/symbols-view-plus/lib/plus/autocomplete-provider.js:68

TypeError: Cannot read property 'substring' of undefined
    at /packages/symbols-view-plus/lib/plus/autocomplete-provider.js:68:37
    at Array.map (native)
    at AutocompleteProvider.getSuggestions (/packages/symbols-view-plus/lib/plus/autocomplete-provider.js:66:82)
    at providers.forEach.provider (/snap/atom/76/usr/share/atom/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:286:58)
    at Array.forEach (native)
    at AutocompleteManager.getSuggestionsFromProviders (/snap/atom/76/usr/share/atom/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:262:21)
    at AutocompleteManager.findSuggestions (/snap/atom/76/usr/share/atom/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:254:23)
```

### Commands

```
  2x -6:36.9.0 core:move-down (input.hidden-input)
     -6:36.3.0 core:paste (input.hidden-input)
     -6:35.6.0 editor:newline (input.hidden-input)
     -6:34.8.0 core:save (input.hidden-input)
     -6:27.2.0 core:move-right (input.hidden-input)
     -6:26.7.0 core:move-down (input.hidden-input)
  3x -6:26.4.0 core:move-left (input.hidden-input)
  5x -6:24.7.0 editor:move-to-end-of-word (input.hidden-input)
     -6:23.5.0 editor:newline (input.hidden-input)
     -6:23 core:save (input.hidden-input)
     -5:16.4.0 snippets:next-tab-stop (input.hidden-input)
     -5:16.4.0 snippets:expand (input.hidden-input)
     -5:16.4.0 editor:indent (input.hidden-input)
     -5:14.2.0 core:move-down (input.hidden-input)
     -5:09.6.0 core:move-up (input.hidden-input)
  2x -5:02.3.0 core:move-right (input.hidden-input)
```

### Non-Core Packages

```
project-viewer 1.2.5 
symbols-tree-view 0.14.0 
symbols-view-plus 0.117.0-plus.1 
toggler 0.3.0 
```

**Comment by aidistan** [comment]
Sorry, failed to reproduce this issue.

The info provided by the stack trace is too limited.
