### ISSUE TITLE
Error when installing on Windows

### ISSUE THREAD

**Issue by ukind** [aidistan/atom-symbols-view-plus#6]
I got an error when i Install the packages, here's the logs

```
> ctags@3.0.0 install C:\Users\YOGISW~1\AppData\Local\Temp\apm-install-dir-116821-7784-whv16y\node_modules\symbols-view-plus\node_modules\ctags
> node-gyp rebuild


C:\Users\YOGISW~1\AppData\Local\Temp\apm-install-dir-116821-7784-whv16y\node_modules\symbols-view-plus\node_modules\ctags>if not defined npm_config_node_gyp (node "A:\Program Files\Atom\resources\app\apm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\YogiswaraUtama\AppData\Local\atom\app-1.10.2\resources\app\apm\bin\\..\node_modules\node-gyp\bin\node-gyp.js" rebuild ) 
C:\Users\YOGISW~1\AppData\Local\Temp\apm-install-dir-116821-7784-whv16y
`-- (empty)


gyp ERR! configure error 
gyp ERR! stack Error: Python executable "C:\Users\YogiswaraUtama\AppData\Local\Programs\Python\Python35\python.EXE" is v3.5.0, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at failPythonVersion (A:\Program Files\Atom\resources\app\apm\node_modules\node-gyp\lib\configure.js:454:14)
gyp ERR! stack     at A:\Program Files\Atom\resources\app\apm\node_modules\node-gyp\lib\configure.js:443:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:204:7)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:827:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "C:\\Users\\YogiswaraUtama\\AppData\\Local\\atom\\app-1.10.2\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\YogiswaraUtama\\AppData\\Local\\atom\\app-1.10.2\\resources\\app\\apm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\YOGISW~1\AppData\Local\Temp\apm-install-dir-116821-7784-whv16y\node_modules\symbols-view-plus\node_modules\ctags
gyp ERR! node -v v4.4.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\YOGISW~1\AppData\Local\Temp\apm-install-dir-116821-7784-whv16y\package.json'
npm WARN apm-install-dir-116821-7784-whv16y No description
npm WARN apm-install-dir-116821-7784-whv16y No repository field.
npm WARN apm-install-dir-116821-7784-whv16y No README data
npm WARN apm-install-dir-116821-7784-whv16y No license field.
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Users\\YogiswaraUtama\\AppData\\Local\\atom\\app-1.10.2\\resources\\app\\apm\\bin\\node.exe" "A:\\Program Files\\Atom\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\YogiswaraUtama\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\YogiswaraUtama\\.atom\\.apmrc" "install" "C:\\Users\\YOGISW~1\\AppData\\Local\\Temp\\d-116821-7784-kxeylf\\package.tgz" "--runtime=electron" "--target=0.37.8" "--arch=ia32" "--global-style"
npm ERR! node v4.4.5
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE

npm ERR! ctags@3.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ctags@3.0.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ctags package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ctags
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ctags
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\YOGISW~1\AppData\Local\Temp\apm-install-dir-116821-7784-whv16y\npm-debug.log
npm ERR! code 1
```

how I could fix it ?

**Comment by aidistan** [comment]
Thanks for trying this package.

As the logs said, the version of Python on your computer (v3.5.0) is too new for Atom (>= v2.5.0 & < 3.0.0).

**Comment by ukind** [comment]
I see, by default, my atom detect Python 3.x when installation process. srry if these a bit of OOT.
but, is there any way to change how atom detect my Python version ?
I installed python versions 2.x and 3.x . and I could run both of them via cmd
Ty

**Comment by aidistan** [comment]
@ukind Try to put the path to python 2.x ahead in the environment variable `PATH` ?

**Comment by aidistan** [comment]
I will reopen this issue once it gets back on track.
